### ISSUE TITLE
Things to do before next milestone

### ISSUE THREAD

**Issue by ramarvab** [airavata-courses/TeamSangam#42]
1. Implement Sessions in user login and homepage.
2. show no  map, if we didn't get data from the forecast algorithm
3. Implement registry and update services accordingly
4. create admin page to display logs
5. Distributed Deployment.

Please update the status by next monday.

**Comment by ramarvab** [comment]
Huge tar files because of adding too many dependencies , remove unnecessary dependencies form pom.xml

**Comment by praddyinstant** [comment]
I have created individual Git Issues for all the above items. Will wait for 1 day and if everyone agrees then will close this issue.
