### ISSUE TITLE
Show no map, if we don't get data from the Run_forecast Service

### ISSUE THREAD

**Issue by praddyinstant** [airavata-courses/TeamSangam#47]
1. Handle all the response codes.
2. If there is no Storm Detected then refresh the map and display no locations.

**Comment by rajasimha1991** [comment]
Updated javascript file so that a fresh map instance will be displayed when a new request is sent.

**Comment by rajasimha1991** [comment]
Based on the response of the HTTP request, if storm exists a new google map will be displayed otherwise a string message will be displayed.
