### ISSUE TITLE
Database choices

### ISSUE THREAD

**Issue by vikaspro90** [airavata-courses/TeamSangam#5]
1. For the login module, I am planning to use MySQL on account of its high compatibility, wide usage in the industry and decent data protection.
2. Need to decide on database for registry.

**Comment by ramarvab** [comment]
We can use mongodb for registry, as it is a nosql database and good for document database. It is consistent and high availability.

Cassandra is eventually consistent but not real time consistent

**Comment by vikaspro90** [comment]
Using MySQL for user database for the aforementioned reasons.
