### ISSUE TITLE
MongoDB docker issue

### ISSUE THREAD

**Issue by ramarvab** [airavata-courses/TeamSangam#52]
I am extracting mongo image using docker pull mongo

and ran the container using the command docker run -it -p 27017:27017 --name mongodb mongo

Next I started dataingest service by deploying the war file  and ran the container by linking mongodb container .

docker run  --name linkmongo  --it -p 8080:8080 --link mongodb:mongodb  -t dataingest

Then I am calling the service from browser but mongo database is not receiving any call from the data ingest service...

In my code, I am referring to MongoDB as localhost:27017, even though the docker image is in the same EC2 host and the port is exposed. It is not able to send requests to Database.

**Comment by ajinkya-dhamnaskar** [comment]
When you are linking containers, you don't need to expose its port in run command. I would suggest log into linkmongo db container using "docker exec -ti 'linkmongo_container_id' bash". To get container id use "docker ps -a" and then troubleshoot the problem.

**Comment by praddyinstant** [comment]
We were able to get around with this by referring the Mongo instance using the **Mongo** Docker name.
We are still looking for a more permanent resolution for this. 
But closing this issue for now.
