### ISSUE TITLE
Multiple tomcat docker images linking issue

### ISSUE THREAD

**Issue by rajasimha1991** [airavata-courses/TeamSangam#64]
We are not able to link multiple tomcat docker images on EC2 instance.  Each tomcat docker container is always listening on 8080 port by default, even though we are exposing different ports for each tomcat image.

**Comment by rajasimha1991** [comment]
Initially we thought that

**Comment by praddyinstant** [comment]
Linking the common docker internal port of each docker 8080 to different Host port solved the issue.
