### ISSUE TITLE
Handle image in the frontend.

### ISSUE THREAD

**Issue by vikaspro90** [airavata-courses/TeamSangam#89]
Need to display the gif image received from the Mesos cluster.

**Comment by vikaspro90** [comment]
The gif can be converted to a base64 string and passed to the frontend. It can then be rendered on the browser. Can you send me that string..?

**Comment by praddyinstant** [comment]
We can generate the URL from backend service using which you can get the GIF file. Can you handle the display of gif file using that URL

**Comment by vikaspro90** [comment]
Well... It would have been great if that worked. But the problem is that, from javascript on our domain, we cannot access an image that is hosted on backend of another domain. To be able to do so, CORS has to be enabled on the domain that serves the image. But that is out of our control. So, we can consider this option out. But it should be possible to download the image on one of our instances using a backend service and then encode the image into base64 string.. What do you think.?

**Comment by praddyinstant** [comment]
I should be able to do it. Rather than solving the CORS issue, it looks a better way to approach this issue. I can download the gif file and encode it to base64 string.
