### ISSUE TITLE
How do you monitor jobs on the Mesos cluster?

### ISSUE THREAD

**Issue by vikaspro90** [airavata-courses/TeamSangam#95]

**Comment by praddyinstant** [comment]
We thought about two approaches
1. To Poll the mesos cluster until the status is returned is Completed.
There were several issues in this blocking approach and the load will be considerably high when lot of jobs are submitted to the application. So we decided  against polling method.

2. We wrote a function which returns the status of a job based on Job ID. So when the user wants an update on the job status. He can click on the update button in the UI, and fetch the latest status on the job.
