### ISSUE TITLE
How do you manage user-selected resubmissions?

### ISSUE THREAD

**Issue by vikaspro90** [airavata-courses/TeamSangam#99]

**Comment by vikaspro90** [comment]
We can do something like this. Whenever a user clicks on a previous job in the table provided, we can load those job details in the job creation form and let the user change the parameters as desired.

**Comment by rajasimha1991** [comment]
Yes, we can load the previous details as you mentioned. We need to call all the services once again for populating the drop downs.

**Comment by praddyinstant** [comment]
Good approach to solve the re-submission for user. But I don't see a point creating the modification you proposed as we are taking the user back to the home page. 

Then it is a feature we need to provide so lets implement it the way you proposed.

**Comment by vikaspro90** [comment]
Implemented as discussed.
